In [2]:
import pandas as pd

df = pd.read_csv("day_wise.csv")

df.head(10)
df["Deaths"].mean()

np.float64(230770.76063829788)

In [3]:
df["Deaths"].max()

np.int64(654036)

In [4]:
df[df["Deaths"] == df["Deaths"].max()]

,Date,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,No. of countries
187,2020-07-27,16480485,654036,9468087,6358362,228693,5415,174623,3.97,57.45,6.91,187

In [5]:
df.isnull().sum()

Date                      0
Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
No. of countries          0
dtype: int64

In [6]:
df["Deaths"].median()

np.float64(204190.0)

In [7]:
df[df["Deaths"] == df["Deaths"].median()]

Empty DataFrame
Columns: [Date, Confirmed, Deaths, Recovered, Active, New cases, New deaths, New recovered, Deaths / 100 Cases, Recovered / 100 Cases, Deaths / 100 Recovered, No. of countries]
Index: []

In [8]:
df["Deaths"].mode()

0          17
1          18
2          26
3          42
4          56
        ...
183    633506
184    639650
185    644517
186    648621
187    654036
Name: Deaths, Length: 188, dtype: int64

In [9]:
df["Deaths"].sum()

np.int64(43384903)